/* Separate licensed SRD catalogs. Load only the requested edition. */
(()=>{'use strict';const pending=new Map();
const types={aberration:'Аберрация',beast:'Зверь',celestial:'Небожитель',construct:'Конструкт',dragon:'Дракон',elemental:'Элементаль',fey:'Фея',fiend:'Исчадие',giant:'Великан',humanoid:'Гуманоид',monstrosity:'Монстр',ooze:'Слизь',plant:'Растение',undead:'Нежить'},sizes={Tiny:'Крошечный',Small:'Маленький',Medium:'Средний',Large:'Большой',Huge:'Огромный',Gargantuan:'Громадный'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function load(e){e=e==='2024'?'2024':'2014';if(!pending.has(e))pending.set(e,fetch('assets/bestiary/srd-monsters-'+e+'.json?v=0117').then(r=>{if(!r.ok)throw Error('Не удалось загрузить бестиарий.');return r.json();}).then(d=>{if(d.edition!==e||!Array.isArray(d.monsters))throw Error('Неверный каталог.');return d.monsters.sort((a,b)=>a.name_ru.localeCompare(b.name_ru,'ru')||a.id.localeCompare(b.id));}).catch(err=>{pending.delete(e);throw err;}));return pending.get(e);}
function filters(p){return {edition:p.get('edition')==='2024'?'2024':'2014',q:(p.get('q')||'').trimStart().toLocaleLowerCase('ru'),cr:p.get('cr')||'all',size:p.get('size')||'all',type:p.get('type')||'all'};}
function query(f){const p=new URLSearchParams({edition:f.edition});for(const k of ['q','cr','size','type'])if(f[k]&&f[k]!=='all')p.set(k,f[k]);return p;}
function filter(list,f){return list.filter(x=>(f.cr==='all'||x.cr===f.cr)&&(f.size==='all'||(x.sizes||[x.size]).includes(f.size))&&(f.type==='all'||x.type===f.type)&&(x.name+' '+x.name_ru+' '+(types[x.type]||'')).toLocaleLowerCase('ru').includes(f.q));}
const symbols={aberration:'◉',beast:'♧',celestial:'✧',construct:'⚙',dragon:'♜',elemental:'✦',fey:'❋',fiend:'♆',giant:'⬟',humanoid:'♟',monstrosity:'◇',ooze:'≋',plant:'❦',undead:'☠'};
function icon(t){return '<span class="srd-type-symbol" aria-hidden="true">'+(symbols[t]||'◇')+'</span>';}
function attribution(){return '<details class="srd-attribution"><summary>Источники и лицензия</summary><p>This work includes material from the System Reference Document 5.1 and System Reference Document 5.2.1 by Wizards of the Coast LLC, available at <a href="https://www.dndbeyond.com/srd" target="_blank" rel="noopener">D&D Beyond</a>. The SRDs are licensed under the <a href="https://creativecommons.org/licenses/by/4.0/legalcode" target="_blank" rel="noopener">Creative Commons Attribution 4.0 International License</a>. Russian labels, selection and formatting: Мир Холэна. Original stat blocks are in English.</p></details>';}
window.HOLEN_SRD={load,types,sizes,esc,filters,filter,query,icon,attribution};})();
