const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const box={window:{},URLSearchParams};vm.createContext(box);
for(const f of ['dnd-data.js','dnd-options-data.js','dnd-option-sources.js','character-wizard-model.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),box);
const {HOLEN_CHARACTER_WIZARD:m,HOLEN_DND:d,HOLEN_DND_OPTIONS:o,HOLEN_OPTION_SOURCES:src}=box.window;
let checks=0;const eq=(a,b)=>{assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)));checks++;},ok=x=>{assert.ok(x);checks++;};
let s=m.fresh();eq(m.steps(s).length,7);eq(d.pointBuyCost(s.sheet.baseAbilities),0);
for(const k of Object.keys(d.abilities))m.change(s,'base:'+k,15);
ok(m.validate(s,4));m.change(s,'abilityMode','standard-array');ok(!m.validate(s,4));
m.change(s,'base:str',8);eq(s.sheet.baseAbilities.cha,15);ok(!m.validate(s,4));
m.change(s,'classId','wizard');eq(m.cls(s).name,'Волшебник');eq(s.sheet.casting,'int');eq(s.sheet.saveProficiencies,['int','wis']);
m.change(s,'level',2);ok(o.availableSubclasses(s.sheet).length>0);ok(m.validate(s,5));
m.change(s,'selectedSubclassId',o.availableSubclasses(s.sheet)[0].id);ok(!m.validate(s,5));
m.change(s,'classId','fighter');eq(s.sheet.selectedSubclassId,'');
m.change(s,'level',3);m.change(s,'selectedSubclassId',o.availableSubclasses(s.sheet)[0].id);
m.change(s,'level',1);eq(s.sheet.selectedSubclassId,'');
m.change(s,'feat',['alert',true]);eq(s.extras.length,0);
m.change(s,'variantHuman',true);m.change(s,'feat',['alert',true]);eq(s.extras,['alert']);
m.change(s,'feat',['actor',true]);eq(s.extras,['alert']);
m.change(s,'speciesId','elf');eq(s.variantHuman,false);eq(s.extras.length,0);
m.change(s,'level',4);m.change(s,'feat',['alert',true]);eq(s.extras,['alert']);
m.change(s,'level',1);eq(s.extras.length,0);
m.change(s,'edition','2024');m.change(s,'backgroundId','acolyte');eq(s.sheet.featIds,['magic-initiate']);eq(s.sheet.skills.insight,1);
m.change(s,'feat',['alert',true]);ok(s.sheet.featIds.includes('alert'));eq(s.extras.length,1);
m.change(s,'feat',['actor',true]);eq(s.extras.length,1);
m.change(s,'speciesId','elf');eq(s.extras.length,0);eq(s.sheet.featIds,['magic-initiate']);
m.change(s,'backgroundId','criminal');ok(!s.sheet.featIds.includes('magic-initiate'));eq(s.sheet.skills.religion,0);
eq(m.budgets(s).style,1);const style=o.editions['2024'].feats.find(f=>f.category==='Fighting Style');m.change(s,'feat',[style.id,true]);ok(s.extras.includes(style.id));
m.change(s,'classId','wizard');eq(s.extras.length,0);eq(m.budgets(s).style,0);
m.change(s,'level',3);ok(m.validate(s,5));m.change(s,'selectedSubclassId',o.availableSubclasses(s.sheet)[0].id);ok(!m.validate(s,5));
m.change(s,'levelMode','xp');m.change(s,'experience',6500);eq(s.sheet.level,5);
m.change(s,'classId','fighter');eq(m.budgets(s).general,1);m.change(s,'experience',14000);eq(m.budgets(s).general,2);
m.change(s,'abilityMode','standard-array');m.change(s,'bonus:con',2);
const p=m.payload(s);eq(p.maxHp,d.hpMaximum(p));eq(p.hp,p.maxHp);eq(p.hitDice,p.level);
eq(p.armorClass,10+d.modifier(p.abilities.dex));eq(p.type,'dnd');
m.change(s,'name','Тест');m.change(s,'selectedSubclassId',o.availableSubclasses(s.sheet)[0].id);ok(!m.validateAll(s));
const raw={...s,extras:['bogus','alert',style.id],sheet:{...s.sheet,selectedSubclassId:'not-a-subclass'},step:999};
const restored=m.restore(raw);eq(restored.step,6);eq(restored.sheet.selectedSubclassId,'');ok(!restored.extras.includes('bogus'));ok(m.validateAll(restored));
m.change(s,'pack','insects');eq(m.steps(s).length,4);ok(m.validate(s,2,[]));m.change(s,'templateId','a');ok(!m.validate(s,2,[{id:'a'}]));
eq(src.sourceFor({},'2014').abbr,'PH14');eq(src.sourceFor({homebrew:true},'2024').abbr,'HB');ok(src.matches({sourceKind:'homebrew'},'2014','homebrew'));ok(!src.matches({},'2014','homebrew'));
console.log('Wizard model and source checks passed: '+checks);