const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),vm=require('node:vm');
(async()=>{const c={window:{}};for(const f of ['dnd-data.js','dnd-options-data.js'])vm.runInNewContext(await fs.readFile(path.join(__dirname,'..',f),'utf8'),c);const d=c.window.HOLEN_DND,o=c.window.HOLEN_DND_OPTIONS;
for(const e of ['2014','2024']){const dir=path.join(__dirname,'../assets/bestiary'),data=JSON.parse(await fs.readFile(path.join(dir,'srd-monsters-'+e+'.json'),'utf8'));assert.equal(data.monsters.length,e==='2014'?317:330);assert.equal(data.format,'holen-srd-index-v1');assert.equal(new Set(data.monsters.map(x=>x.id)).size,data.count);assert((await fs.stat(path.join(dir,'srd-monsters-'+e+'.json'))).size<60000);const chunks=new Map();for(const card of data.monsters){assert(!('block_text' in card));assert(/^\d{2}$/.test(card.chunk));if(!chunks.has(card.chunk)){const chunk=JSON.parse(await fs.readFile(path.join(dir,'srd-details-'+e+'-'+card.chunk+'.json'),'utf8'));assert.equal(chunk.edition,e);assert.equal(chunk.translation?.author,'OmnisGM');assert.equal(chunk.translation?.license,'CC BY 4.0');assert(chunk.monsters.length<=20);chunks.set(card.chunk,chunk.monsters);}const matches=chunks.get(card.chunk).filter(m=>m.id===card.id);assert.equal(matches.length,1);const m={...card,...matches[0]};assert(m.name_ru&&m.block_text&&m.source_page>250);assert.equal(m.text_language,'ru');assert(m.block_text.startsWith(m.name_ru+'\n'));assert(/Класс [дД]оспеха:/.test(m.block_text));assert(/Хиты:/.test(m.block_text));assert(!/Hit Points:|Armor Class:|Actions\n|Traits\n/.test(m.block_text));assert.equal(Number(m.block_text.match(/Класс [дД]оспеха:\s*(\d+)/)[1]),m.ac);assert.equal(Number(m.block_text.match(/Хиты:\s*(\d+)/)[1]),m.hp);assert(m.ac>0&&m.hp>0&&m.abilities.length===6);assert(m.abilities.every(n=>Number.isInteger(n)&&n>=1&&n<=30));assert(/^(0|[1-9]\d*|1\/[248])$/.test(m.cr));assert(m.sizes.length);}
assert.equal([...chunks.values()].flat().length,data.count);
const choices=o.editions[e];assert.equal(choices.spells.length,e==='2014'?319:339);assert.equal(choices.feats.length,e==='2014'?42:75);for(const bg of choices.backgrounds)for(const k of bg.skills)assert(d.skills.some(x=>x[0]===k),k);assert(choices.spells.every(x=>x.level>=0&&x.level<=9));}
assert(!o.availableSubclasses(d.blank('2024','fighter')).length);assert.equal(o.availableSubclasses(d.normalize({...d.blank('2024','fighter'),level:3})).length,4);assert.equal(o.availableSubclasses(d.blank('2014','cleric')).length,7);const actor=o.editions['2024'].feats.find(x=>x.id==='actor');assert(!o.featEligibility(actor,d.normalize({...d.blank('2024'),level:4})).eligible);assert(o.featEligibility(actor,d.normalize({...d.blank('2024'),level:4,baseAbilities:{cha:13}})).eligible);

const corrections=[];for(const e of ['2014','2024']){const dir=path.join(__dirname,'../assets/bestiary');for(const f of await fs.readdir(dir))if(f.startsWith('srd-details-'+e+'-'))corrections.push(...JSON.parse(await fs.readFile(path.join(dir,f),'utf8')).monsters);}const stat=id=>corrections.find(m=>m.id===id).block_text;assert.match(stat('dnd-2014-merrow'),/11 \(2к6 \+ 4\)/);assert.match(stat('dnd-2024-awakened-tree'),/14 \(3к6 \+ 4\)/);assert.match(stat('dnd-2024-axe-beak'),/6 \(1к8 \+ 2\)/);assert.match(stat('dnd-2024-stone-giant'),/Реакции[\s\S]*11 \(1к10 \+ 6\)/);assert.match(stat('dnd-2024-aboleth'),/Использований: 3 \(4 в логове\)/);
console.log('PASS data: 647 unique statblocks, fields, pages, all option IDs, spell counts and prerequisite gates');
})().catch(e=>{console.error(e);process.exit(1)});
